name: CI Pipeline

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # repository
    - name: Check out repository code
      uses: actions/checkout@v3

    # Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # DVC
    - name: Pull DVC
      run: |
        dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    #  flake8 
    - name: Run flake8
      run: |
        pip install flake8
        flake8 

    #  pytest
    - name: Run tests
      run: |
        pytest

  # This workflow contains a single job called "deploy"
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: "   "
        with:
          service-id: ${{ secrets.SERVICE_ID }} 
          api-key: ${{ secrets.RENDER_API_KEY }}